spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Maids.cc?createDatabaseIfNotExist=true
    username: root
    password: root
    driver_class_name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl_auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always